### ISSUE TITLE
Containerization of model serving

### ISSUE THREAD

**Issue by alexpotv** [alexpotv/FishFinder#25]
Create a Docker container with a REST API for interacting with the model.

## TODO

- [x] Document the REST API for the model
- [x] Implement the REST API
- [x] Test the REST API
- [x] Encapsulate into Docker container

**Comment by alexpotv** [comment]
## Tests TODO

- [ ] Mock model (labels and predictions)
- [ ] Add test cases for both detections and no-detections
- [ ] Add testing workflow

**Comment by alexpotv** [comment]
Fixed by #29
