### ISSUE TITLE
Publish report upon completion of model training

### ISSUE THREAD

**Issue by alexpotv** [alexpotv/FishFinder#8]
# Publish report upon completion of model training

Publish a report as a PR comment upon creation of the PR, after the training workflow has been executed.

## TODOs

- [ ] Select which information to display within the report
- [ ] Add generating scripts/stages (if necessary)
- [ ] Add publishing stage to DVC pipeline
